import requests
from typing import List, Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from .client import CursorClient

class Artifact:
    """
    Represents a file artifact generated by an agent.

    Artifacts are files produced during a run that persist in the agent's
    workspace. This class provides metadata and methods to download the
    artifact content.

    Parameters
    ----------
    client : CursorClient
        The HTTP client used for API communication.
    agent_id : str
        The unique identifier of the agent that produced this artifact.
    data : dict
        Raw artifact metadata from the API.

    Attributes
    ----------
    path : str
        Relative path of the artifact in the workspace (e.g., 'artifacts/file.txt').
    size_bytes : int
        Size of the artifact in bytes.
    updated_at : str
        ISO 8601 timestamp of the artifact's last modification.

    Examples
    --------
    >>> artifacts = agent.list_artifacts()
    >>> for art in artifacts:
    ...     content = art.download_content()
    ...     with open(os.path.basename(art.path), "wb") as f:
    ...         f.write(content)
    """

    def __init__(self, client: 'CursorClient', agent_id: str, data: Dict[str, Any]):
        self.client = client
        self.agent_id = agent_id
        self.path: str = data.get("path", "")
        self.size_bytes: int = data.get("sizeBytes", 0)
        self.updated_at: str = data.get("updatedAt", "")

    def get_download_url(self) -> str:
        """
        Retrieve a temporary 15-minute presigned S3 URL for this artifact.

        Returns
        -------
        str
            A temporary URL that can be used to download the file directly.
        """
        res = self.client._get(f"/agents/{self.agent_id}/artifacts/download", params={"path": self.path})
        return res.get("url", "")

    def download_content(self) -> bytes:
        """
        Fetch the raw byte content of the artifact.

        This method first retrieves the presigned URL and then performs
        an HTTP GET request to download the file data.

        Returns
        -------
        bytes
            The raw content of the file.

        Raises
        ------
        requests.exceptions.RequestException
            If the download request fails.
        """
        url = self.get_download_url()
        if not url:
            raise ValueError(f"Could not retrieve download URL for artifact {self.path}")
            
        resp = requests.get(url, stream=True)
        resp.raise_for_status()
        return resp.content

    def __repr__(self) -> str:
        return f"<Artifact path={self.path!r} size={self.size_bytes}B>"


class ArtifactManager:
    """
    Deprecated manager for retrieving artifacts.
    
    Provided for backward compatibility. New code should use 
    :meth:`Agent.list_artifacts` directly.
    """
    def __init__(self, client: 'CursorClient', agent_id: str):
        self.client = client
        self.agent_id = agent_id

    def list(self) -> List[Artifact]:
        """
        List artifacts produced by an agent.

        Returns
        -------
        list of Artifact
            A list of ``Artifact`` objects.

        See Also
        --------
        cursorconnect.agent.Agent.list_artifacts : The modern equivalent.
        """
        res = self.client._get(f"/agents/{self.agent_id}/artifacts")
        return [Artifact(self.client, self.agent_id, item) for item in res.get("items", [])]
