"""Account-level typed objects for the CursorConnect SDK.

This module provides dataclasses for the /me, /models, /repositories, and
run-result API responses.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .conversation import Conversation


@dataclass
class User:
    """
    Authenticated user metadata returned by the ``/me`` endpoint.

    Parameters
    ----------
    api_key_name : str
        The name of the API key used for authentication.
    created_at : str
        ISO 8601 timestamp of when the API key was created.
    user_email : Optional[str], optional
        The user's primary email address, by default ``None``.

    Examples
    --------
    >>> user = Cursor.me(api_key="sk-...")
    >>> print(user.api_key_name)
    Production API Key
    """

    api_key_name: str
    created_at: str
    user_email: Optional[str] = None


@dataclass
class Repository:
    """
    A GitHub repository accessible to the authenticated user.

    Parameters
    ----------
    url : str
        The full HTTPS URL of the repository
        (e.g. ``"https://github.com/org/repo"``).
    name : Optional[str], optional
        The short repository name (``"org/repo"``), by default ``None``.
    description : Optional[str], optional
        A human-readable description of the repository, by default ``None``.
    is_private : Optional[bool], optional
        ``True`` when the repository is private, by default ``None``.
    default_branch : Optional[str], optional
        The name of the default branch (e.g. ``"main"``), by default ``None``.
    """

    url: str
    name: Optional[str] = None
    description: Optional[str] = None
    is_private: Optional[bool] = None
    default_branch: Optional[str] = None


@dataclass
class RunResult:
    """
    The terminal result of a completed agent run.

    Returned by :meth:`~cursorconnect.run.Run.wait` once the run reaches a
    terminal state.

    Parameters
    ----------
    run_id : str
        The unique identifier of the run that completed.
    status : str
        The terminal status.  One of ``"FINISHED"``, ``"ERROR"``,
        ``"CANCELLED"``, or ``"EXPIRED"``.
    conversation : Conversation, optional
        Typed conversation history for the run, by default ``None``.
    error_message : Optional[str], optional
        A human-readable error description populated when *status* is
        ``"ERROR"``, by default ``None``.
    agent_id : Optional[str], optional
        The unique identifier of the agent that produced this run result, by default ``None``.
    artifacts : Optional[List[Any]], optional
        A list of artifacts generated by the agent during the run, by default ``None``.
    """

    run_id: str
    status: str
    conversation: Optional["Conversation"] = None
    error_message: Optional[str] = None
    agent_id: Optional[str] = None
    artifacts: Optional[List[Any]] = None
    result_text: Optional[str] = None
