"""
Types for the Mesh orchestration layer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, List, Optional, Any, Union

from .options import CloudOptions
from .models import ModelSelection
from .account import RunResult

if TYPE_CHECKING:
    from ..agent import Agent
    from ..artifact import Artifact


@dataclass
class MeshTask:
    """
    A single task to be executed within a Mesh.

    Parameters
    ----------
    name : str
        A unique identifier for this task (e.g., "auth-agent", "frontend").
    prompt : str
        The instruction for the agent to execute.
    cloud : Optional[CloudOptions], optional
        Cloud options specific to this task. Overrides the Mesh's default cloud options.
    model : Optional[Union[str, ModelSelection]], optional
        Model selection specific to this task. Overrides the Mesh's default model.
    """
    name: str
    prompt: str
    cloud: Optional[CloudOptions] = None
    model: Optional[Union[str, ModelSelection]] = None


@dataclass
class MeshResult:
    """
    The result of a single task executed within a Mesh.

    Parameters
    ----------
    name : str
        The name of the task.
    agent : Agent
        The Agent instance that executed the task.
    run_result : RunResult
        The terminal run result from the agent's execution.
    artifacts : List[Artifact]
        The artifacts generated by the agent during the run.
    """
    name: str
    agent: "Agent"
    run_result: RunResult
    artifacts: List["Artifact"] = field(default_factory=list)
